**NUMBER**
digit = "0"|"1"|"2"|"3"|"4"|"5"|"6"|"7"|"8"|"9"; 
sign = "+"|"-";
integer = digit, {digit};
decimal = integer,".", digit, {digit};

letter = "a"|"b"|"c"|"d"|"e"|"f"|"g"|"h"|"i"|"j"|"k"|"l"|"m"
       | "n"|"o"|"p"|"q"|"r"|"s"|"t"|"u"|"v"|"w"|"x"|"y"|"z"
       | "A"|"B"|"C"|"D"|"E"|"F"|"G"|"H"|"I"|"J"|"K"|"L"|"M"
       | "N"|"O"|"P"|"Q"|"R"|"S"|"T"|"U"|"V"|"W"|"X"|"Y"|"Z"
       | "_";

**UNITS**
base_unit = "g"|"m"|"s"|"A"|"K"|"mol"|"cd"|"L";
derived_unit = "N"|"J"|"Hz"|"Pa"|"V"|"W"|"rad"|"C"|"ohm"|"F"|"Wb"|"S"|"T"|"H"|"lm"|"lx"|"Bq"|"Gy"|"Sv";
misc_unit = "degC"|"min"|"h"|"day"|"deg";
prefix = "Q"|"R"|"Y"|"Z"|"E"|"P"|"T"|"G"|"M"|"k"|"h"|"da"|"d"|"c"|"m"|"u"|"n"|"p"|"f"|"a"|"z"|"y"|"r"|"q";

unit_atom = ([prefix], (base_unit | derived_unit)) | misc_unit; # handles prefix seperately from misc
unit_exponent = unit_atom, ["^", integer]; # allows units to be written with powers e.g. m/s^2, kg^2, etc.
unit = unit_exponent, {("*"|"/"), unit_exponent}; <-- main dimensional unit 

**SCIENTIFIC NOTATION**
exponent = "e"|"E";
sci_not = (decimal | integer), [exponent, [sign], integer]; <-- main numerical unit

**EXPRESSIONS, IDENTIFIERS, ARGUMENTS**
identifier = letter, {letter | digit};
arglist = expression, {",", expression};
assignment = identifier, "=", expression;
statement = assignment | expression;

expression = term, {("+"|"-"), term}; # handles adding/subtracting  terms together (e.g. 3x + 2x + 3y) --> AS
term = factor, {("*"|"/"), factor}; # handles variables/numbers being multiplied/divided together (e.g. 3 * x, 2 * x, 3 * y) --> MD
factor = unary, ["^", factor]; # handles exponentiation, right-associative --> E
unary = [sign], primary; # handles signs (+/-) --> allows for putting - in front of expressions e.g. -(5+3)
primary = sci_not, [unit] | "(", expression, ")" | identifier, ["(", [arglist], ")"]; # a number followed by a unit, an expression (in brackets), or a variable/function name

**SPECIAL IDENTIFIERS**
pi = 3.141592653589
e = 2.718281828459